### PR TITLE
init project

### PR DESCRIPTION
**Pull request by haltn-3346**
## Related Tickets
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/52013)

## WHAT (optional)
- Change number items `completed/total` in admin page.

## HOW
- I edit js file, inject not_vary_normal items in calculate function.

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

### CODE REVIEW

**Comment by ngocha198** [comment]
ready

**Comment by haltn-3346** [comment]
ready

**Comment by trongxt-0611** [comment]
ready

**Comment by ngocvt-0484** [comment]
image
e fix comment này để pass CI nhé

**Comment by ngocvt-0484** [comment]
commented

**Comment by haltn-3346** [comment]
ready

**Pull request merged**
